apiVersion: apps/v1
kind: Deployment
metadata:
  name: Githubaction
  labels:
    app: Githubaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Githubaction
  template:
    metadata:
      labels:
        app: Githubaction
    spec:
      containers:
        - name: Githubaction
          image: 920100595657.dkr.ecr.us-east-1.amazonaws.com/githubaction:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080